#:schema node_modules/wrangler/config-schema.json
name = "sublink-work2"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "82dffeb6953d427588f88fffd642a473" }
]

[assets]
directory = "./public"
